<h2>NumPy</h2>

* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy stands for Numerical Python.

In [2]:
import numpy as np #np is like a nick name for numpy library to make it easy to access it can be any thing 
#it dosen't have to be np but it is a well used practice

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) #the numpy function converts the values into numpy array

In [4]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
type(a)

numpy.ndarray

In [6]:
#the variable a is a numpy array

<h3>0-D Array</h3>

In [7]:
b = np.array(32)

In [8]:
print(b)

32


In [9]:
type(b)

numpy.ndarray

In [10]:
b.ndim #ndim tels the diamension of an array

0

<h3>1-D Array</h3>

In [11]:
c = np.array([1, 2, 3, 4, 5])

In [12]:
print(c)

[1 2 3 4 5]


In [13]:
type(c)

numpy.ndarray

In [14]:
c.ndim

1

<h3>2-D Array</h3>

In [15]:
d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [16]:
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
type(d)

numpy.ndarray

In [18]:
d.ndim

2

<h3>3-D Array</h3>

In [19]:
e = np.array([[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]], [[6, 7, 8, 9, 10], [16, 17, 18, 19, 20]]])

In [20]:
print(e)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [21]:
type(e)

numpy.ndarray

In [22]:
e.ndim

3

In [23]:
# we can also define the diamension of array during creation without adding values
#array can be of any number of diamensions
f = np.array([1, 2, 3, 4, 5], ndmin = 5)

In [24]:
print(f)

[[[[[1 2 3 4 5]]]]]


In [25]:
type(f)

numpy.ndarray

In [26]:
f.ndim

5

<h3> NumPy array indexing</h3>

* Np array indexing work same as list indexing

* it starts fom zero and the reverse indexing starts from -1

* there is no indexing for 0-D Array

In [27]:
# 1-D array indexing

print(c[3])
print(c[2])
c

4
3


array([1, 2, 3, 4, 5])

In [28]:
# 2-D array indexing

print(d[0, 1]) # first value gives access to the first array and second value gives access to values of array

print(d[1, 3])# now the first value access the second array in the array and second value gives access to value of array

d

2
9


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
# 3-D array indexing

print(e[0, 0, 3])

print(e[0, 1, 3])

print(e[1, 0, 3])

print(e[1, 1, 3])

e

4
14
9
19


array([[[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]],

       [[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]])

<h3>Array Slicing</h3>

* Slicing in python means taking elements from one given index to another given index.

* We pass slice instead of index like this: [start:end].

* We can also define the step, like this: [start:end:step].

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

In [30]:
c

array([1, 2, 3, 4, 5])

In [29]:
# 1-d array slicing

c[1:3]

array([2, 3])

In [31]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
#2-d array slicing

print(d[0:2, 1:3])

print(d[1, 1:3]) # first selects the array and the second selects the value of the array

[[2 3]
 [7 8]]
[7 8]


In [36]:
e

array([[[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]],

       [[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]])

In [39]:
#3-d array slicing

print(e[0:2, 0:2, 1:3]) #the first selects the first set of array, second diamension selects the array from the the first array and
# third selscts the value inside

[[[ 2  3]
  [12 13]]

 [[ 7  8]
  [17 18]]]


In [32]:
e.dtype # this tells the type of values inside the array

dtype('int64')

In [40]:
# we can also specify the datatype of the values in the array

g = np.array([1, 2, 3, 4, 5], dtype = 'S') # now the value will be considered as string type

In [41]:
g 

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [42]:
g.dtype

dtype('S1')

In [36]:
# another way to convart the value is astype

h = g.astype('i') # now the value will be converted to integer type

In [37]:
h

array([1, 2, 3, 4, 5], dtype=int32)

In [38]:
h.dtype

dtype('int32')

<h3>copy and view function</h3>

1. <h4>copy function</h4>

    * copy() function copys the value of the array to another variable 

    * the original and the copy are two different variable

    * changes in the copy will not effect the original and change in original will not effect the copy
    
    * in copy the copy owns the data that is the data belongs to it alone

2. <h4>view function</h4>

    * view() function copy the value of the array

    * but the copy and the original are one in the same 

    * change in the copy will effect the original and change in original will effect the copy
    
    * in view the copy shares the data with the original

In [43]:
c

array([1, 2, 3, 4, 5])

In [44]:
i = c.copy()

In [45]:
i

array([1, 2, 3, 4, 5])

In [46]:
i[0] = 10

In [48]:
i

array([10,  2,  3,  4,  5])

In [49]:
c

array([1, 2, 3, 4, 5])

In [50]:
# change in copy dident effect the original

In [52]:
c[3] = 33

In [53]:
c

array([ 1,  2,  3, 33,  5])

In [54]:
i

array([10,  2,  3,  4,  5])

In [55]:
# change in orginal diden't effect the copy

In [56]:
j = c.view()

In [57]:
j

array([ 1,  2,  3, 33,  5])

In [59]:
c

array([ 1,  2,  3, 33,  5])

In [60]:
j[0] = 11

In [61]:
j

array([11,  2,  3, 33,  5])

In [62]:
c

array([11,  2,  3, 33,  5])

In [63]:
# change in copy changed the original to 

In [64]:
c[1] = 22

In [65]:
c

array([11, 22,  3, 33,  5])

In [66]:
j

array([11, 22,  3, 33,  5])

In [60]:
# change in original changed the copy to 

In [61]:
# there is a base function that returns none if the array owns the data if not then it returns the array

In [67]:
print(i.base)
print(j.base)

None
[11 22  3 33  5]


In [63]:
# j doesnot own the data therefore it returned the array instead of non 

In [64]:
d.shape

(2, 5)

<h3> Array Reshaping</h3>

* Reshaping means changing the shape of an array.

* shape of an array is the number of elements in each dimension.

* reshaping we can add or remove dimensions or change number of elements in each dimension.

In [65]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
len(a)

10

In [67]:
new_a = a.reshape(3, 3) # since we have 10 elements in the array so the shape should corresponding to number of elements
# since there are 10 elements shape should be 2x5 or 5x2 or 10x1 or 2x1x5. the above shape 3x3 is not relevent that is why 
# it will throw an error

ValueError: cannot reshape array of size 10 into shape (3,3)

In [68]:
new_a = a. reshape(2, 1, 5)

In [69]:
new_a

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

In [70]:
new_a_2 = a.reshape(5, 2)

In [71]:
new_a_2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [83]:
new_a_2.shape

(5, 2)

In [72]:
new_a_1 = a.reshape(5, 2)

<h3>Numpy joining</h3>

* it menas that combining two array into one array and storing it in another

In [73]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
c

array([11, 22,  3, 33,  5])

In [75]:
con = np.concatenate((a, c)) # we pass both array in concat function and this will return us a combination of the two array

In [76]:
con

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22,  3, 33,  5])

In [77]:
new_a_2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [81]:
new_a_1 = np.array(([[1], [2], [3], [4], [5]])) 

In [82]:
new_a_1.shape

(5, 1)

In [87]:
# combining 2-D array

con_1 = np.concatenate((new_a_2, new_a_1), axis=1) # in 2-D array we have to specifiy wether to combine via row or column
# axis 0 represents row
#axis 1 represents column
# either the number of rows should be same or the number of columns
# if number of rows are same and column are different then we concatinate it using column axis i.e. axis=1
# if number of rows are different and column are same then we concatinate it using row axis i.e. axis=0

In [85]:
con_1 #in this the number of rows were same but the no of columns were different and when concatinated them and the 
#additional columns were added

array([[ 1,  2,  1],
       [ 3,  4,  2],
       [ 5,  6,  3],
       [ 7,  8,  4],
       [ 9, 10,  5]])

In [88]:
test = np.array(([[1, 2], [3, 4]]))

In [89]:
test.shape

(2, 2)

In [90]:
con_2 = np.concatenate((new_a_2, test), axis=0)

In [91]:
con_2
#in this the number of columns were same but the no of rows were different and when concatinated them and since the no of
# row,s were different it concatinated to form rows``

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4]])

In [101]:
#joining using stack function
# unlike concatinate function stack function concatinates on a axis
# if the axis is not passed it is by default taken as 0

In [102]:
a_1 = np.array(([44, 55, 66, 77, 88]))

In [103]:
a_1

array([44, 55, 66, 77, 88])

In [104]:
c

array([11, 22,  3, 33,  5])

In [106]:
c_1 = np.stack((c, a_1))

In [107]:
c_1

array([[11, 22,  3, 33,  5],
       [44, 55, 66, 77, 88]])

In [109]:
c_2 = np.stack((c, a_1), axis=1) 

In [111]:
c_2 # as in the output the stack function has concatinated the two row arrays in column fasion and given the result

array([[11, 44],
       [22, 55],
       [ 3, 66],
       [33, 77],
       [ 5, 88]])

<h3>splitting array</h3>

* there are multiole split functions in numpy

* split(), array_split(), hsplit(), vsplit()

* in the function we pass the array to be split and the number of times to split it

* it will return us an array which contains split array in it

In [112]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
spl = np.split(a, 5)

In [114]:
spl

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [115]:
# if we pass a split that is different like 6 there are not wnough numbers to perform this split
# in perfect values here split function will give an error here we cn use array split function 
# array_split function will compensate for the missing values on its own

In [117]:
spl_1 = np.split(a, 6) # because there cannot be equal divisions the function returns an error

ValueError: array split does not result in an equal division

In [118]:
spl_1 = np.array_split(a, 6) # this function will componsate the missing values and give us a split

In [120]:
spl_1 # array_split function performs the split and to componsate it splits the last two values in single array
# to complwte the split

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10])]

In [122]:
# we can perform split based on axis also

spl_2 = np.split(a, 2, axis=1)
# since a is a 1-D array it threw an error

IndexError: tuple index out of range

In [123]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [148]:
spl_2 = np.split(d, 5, axis=1)

In [125]:
spl_2

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [128]:
spl_3 = np.array_split(d, 4, axis=1)

In [129]:
spl_3

[array([[1, 2],
        [6, 7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [145]:
# hsplit splits according to 1 axis
# just like split it doenot componsate for less values
spl_4 = np.hsplit(d, 5)

In [146]:
spl_4

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [142]:
con_1

array([[ 1,  2,  1],
       [ 3,  4,  2],
       [ 5,  6,  3],
       [ 7,  8,  4],
       [ 9, 10,  5]])

In [149]:
# vsplit splits based on row
spl_5 = np.vsplit(con_1, 5)

In [150]:
spl_5

[array([[1, 2, 1]]),
 array([[3, 4, 2]]),
 array([[5, 6, 3]]),
 array([[7, 8, 4]]),
 array([[ 9, 10,  5]])]

<h3> array sorting</h3>

* sort function is used to get a sorted array 

* sort function just returns the copy of the array and leaves the original the same


In [153]:
c

array([11, 22,  3, 33,  5])

In [154]:
print(np.sort(c)) # the sorted array has been printed 

[ 3  5 11 22 33]


In [156]:
c # the original array is uneffected

array([11, 22,  3, 33,  5])

In [157]:
con_1

array([[ 1,  2,  1],
       [ 3,  4,  2],
       [ 5,  6,  3],
       [ 7,  8,  4],
       [ 9, 10,  5]])

In [160]:
# sorting 2-D array

print(np.sort(con_1)) # in 2-D array each array inside will be sorted seperately 

[[ 1  1  2]
 [ 2  3  4]
 [ 3  5  6]
 [ 4  7  8]
 [ 5  9 10]]


<h3> Array filter</h3>

* array filter means to form a array suing specific values from another array

* it is done using true false list

In [161]:
c

array([11, 22,  3, 33,  5])

In [162]:
fil = [True, True, False, True, False]

In [165]:
filtered_array = c[fil]

In [166]:
filtered_array # the values that are true has been stored and rest have been deducted

array([11, 22, 33])

In [169]:
# creating firter list from the array itself using conditional operator

fil_1 = c > 10

In [171]:
fil_1 # the true false list has been created directly from the array

array([ True,  True, False,  True, False])